### ISSUE TITLE
exception when running vector 

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#316] opened 2016-04-27 13:39 UTC
Run the following example: http://cartodb.github.io/deep-insights.js/examples/airbnb_and_closest_metro_vector.html

it raises the following stack trace.

Cateogry widgets are not loaded 

```
deep-insights.uncompressed.js:88994 Uncaught Error: Couldn't create dimension: column closest_metro_line doesn't exist.cartodb.d3.extend._createDimension @ deep-insights.uncompressed.js:88994cartodb.d3.extend.getValues @ deep-insights.uncompressed.js:88920CategoryGeoJSONDataProvider.getData @ deep-insights.uncompressed.js:40895(anonymous function) @ deep-insights.uncompressed.js:41025L.Mixin.Events.fireEvent @ deep-insights.uncompressed.js:12271(anonymous function) @ deep-insights.uncompressed.js:89283L.Mixin.Events.fireEvent @ deep-insights.uncompressed.js:12283(anonymous function) @ deep-insights.uncompressed.js:90378(anonymous function) @ deep-insights.uncompressed.js:89717(anonymous function) @ deep-insights.uncompressed.js:71646event @ deep-insights.uncompressed.js:70155respond @ deep-insights.uncompressed.js:71599XMLHttpRequest.send (async)xhr.send @ deep-insights.uncompressed.js:71649xhr.(anonymous function) @ deep-insights.uncompressed.js:71635d3_xhr @ deep-insights.uncompressed.js:71657d3.json @ deep-insights.uncompressed.js:79187cartodb.d3.extend.getGeometry @ deep-insights.uncompressed.js:89733cartodb.d3.extend.getTile @ deep-insights.uncompressed.js:89714(anonymous function) @ deep-insights.uncompressed.js:89767cartodb.d3.extend._processQueue @ deep-insights.uncompressed.js:89766(anonymous function) @ deep-insights.uncompressed.js:89741setTimeout (async)cartodb.d3.extend._setReady @ deep-insights.uncompressed.js:89739cartodb.d3.extend.setURL @ deep-insights.uncompressed.js:89747L.CartoDBd3Layer.L.TileLayer.extend.setProvider @ deep-insights.uncompressed.js:89235L.CartoDBd3Layer.L.TileLayer.extend.setUrl @ deep-insights.uncompressed.js:89238CartoDBd3Layer.extend._onTileJSONChanged @ deep-insights.uncompressed.js:43044triggerEvents @ deep-insights.uncompressed.js:616triggerApi @ deep-insights.uncompressed.js:601eventsApi @ deep-insights.uncompressed.js:400Events.trigger @ deep-insights.uncompressed.js:591_.extend.set @ deep-insights.uncompressed.js:760ModelUpdater._updateLayerGroupModel @ deep-insights.uncompressed.js:50714ModelUpdater.updateModels @ deep-insights.uncompressed.js:50707(anonymous function) @ deep-insights.uncompressed.js:52590ajaxOptions.success @ deep-insights.uncompressed.js:52198fire @ deep-insights.uncompressed.js:5697self.fireWith @ deep-insights.uncompressed.js:5809done @ deep-insights.uncompressed.js:10862(anonymous function) @ deep-insights.uncompressed.js:11203
```

**Comment by fdansv** [comment] 2016-04-27 13:43
duplicate of https://github.com/CartoDB/Windshaft-cartodb/issues/427

**Closed** 2016-04-27 15:46 UTC
