### ISSUE TITLE
Filtering on widgets when having "ñ" fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#462] opened 2016-10-11 09:33 UTC
@saleiva commented on [Mon Oct 03 2016](https://github.com/CartoDB/cartodb/issues/9976)

underscore:172 Uncaught TypeError: Cannot read property 'toString' of null

---

@xavijam commented on [Mon Oct 03 2016](https://github.com/CartoDB/cartodb/issues/9976#issuecomment-251091474)

Potentially a deep-insights bug, taking a look.

**Comment by donflopez** [comment] 2016-10-11 14:38
Where should be the character ñ? In the column name to be filtered?

In that case, how can I get a ñ in there?

Thank you!

**Comment by saleiva** [comment] 2016-10-11 14:42
- Create a table with 2 columns, the_geom, type
- Add 2 points in 0,0 for example
- set type to "ESPAÑA" in one of them, and "FRANCE" in the other one
- Add a widget to filter by the type column
- Click on ESPAÑA.

**Comment by donflopez** [comment] 2016-10-13 08:48
I can't reproduce it.

This is my table:
<img width="486" alt="screen shot 2016-10-13 at 10 46 00" src="https://cloud.githubusercontent.com/assets/463462/19342486/571d5bd4-9132-11e6-808b-c3c21cc0aa58.png">

This is the widget:
<img width="287" alt="screen shot 2016-10-13 at 10 47 02" src="https://cloud.githubusercontent.com/assets/463462/19342499/67d46224-9132-11e6-8bd9-59203b5378e1.png">

And if I click on ESPAÑA it works ok.

**Comment by saleiva** [comment] 2016-10-14 15:32
Did you try both, within the builder and the public view of the map?

**Comment by donflopez** [comment] 2016-10-14 15:38
Yes! Builder and embed, autostyling and filtering. I've just tried it again.

**Comment by saleiva** [comment] 2016-10-14 15:46
well, close it then. Will report it again if it happens!

**Comment by donflopez** [comment] 2016-10-14 15:47
Ok! Maybe it has been fixed with other changes :)

**Closed** 2016-10-14 15:48 UTC
